project:
  type: website

website:
  site-url: https://stat210a.berkeley.edu/fall-2024/
  google-analytics: G-B8G2041HSB
  sidebar:
    style: docked
    title: "Stat 210a"
    logo: assets/stat_bear.png
    tools:
      - icon: github
        href: https://github.com/berkeley-stat210a/fall-2024
    contents:
      - href: index.qmd
        text: Home / Schedule
      - href: syllabus.qmd
        text: Syllabus
      - href: calendar.qmd
        text: Calendar
      - section: "Units"
        contents:
          - units/unit1.qmd
          - units/unit2.ipynb
          - units/unit3.qmd
      - href: data.qmd
        text: Datasets
      - href: license.qmd
        text: License
          

format:
  html:
    theme: cosmo
    css: assets/styles.css
    toc: true
